const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const state={inventory:[{name:'Яйца',qty:'6 шт.',icon:'🥚'},{name:'Помидоры',qty:'3 шт.',icon:'🍅'},{name:'Сыр',qty:'200 г',icon:'🧀'},{name:'Курица',qty:'500 г',icon:'🍗'},{name:'Сливки',qty:'200 мл',icon:'🥛'}],shopping:[{name:'Шампиньоны',qty:'300 г',icon:'🍄'},{name:'Картофель',qty:'1 кг',icon:'🥔'},{name:'Лук',qty:'2 шт.',icon:'🧅'}]};
let recipes=[{name:'Омлет с овощами',time:'15 мин',need:['яйца','помидоры','сыр'],icon:'🍳'},{name:'Курица с сыром',time:'30 мин',need:['курица','сыр'],icon:'🍗'},{name:'Запеканка',time:'35 мин',need:['яйца','сыр'],icon:'🥘'},{name:'Паста с курицей и грибами',time:'25 мин',need:['курица','шампиньоны','сливки'],icon:'🍝'},{name:'Картофель с курицей',time:'40 мин',need:['курица','картофель','лук'],icon:'🥔'},{name:'Домашний майонез',time:'10 мин',need:['яйца','масло','горчица','лимон'],icon:'🥣'}];
const norm=s=>String(s).toLowerCase().replace(/ё/g,'е');const have=n=>state.inventory.some(x=>norm(x.name).includes(norm(n))||norm(n).includes(norm(x.name)));function recalc(){recipes=recipes.map(r=>({...r,ready:r.need.every(have)}))}
function card(r){return `<article class="recipe"><h3>${r.icon} ${r.name}</h3><p>${r.ready?t('all'):`${t('missing')} ${r.need.filter(x=>!have(x)).join(', ')}.`}</p><div class="recipe-actions"><small>⏱ ${r.time}</small>${r.ready?`<button class="outline cook" data-name="${r.name}">${t('open')}</button>`:`<span class="buy-label">${t('buy')}</span>`}</div></article>`}
function renderRecipes(){recalc();$('#readyRecipes').innerHTML=recipes.filter(r=>r.ready).map(card).join('');$('#buyRecipes').innerHTML=recipes.filter(r=>!r.ready).map(card).join('');$('#readyCount').textContent=recipes.filter(r=>r.ready).length;$('#allRecipes').innerHTML=recipes.map(card).join('')+`<button class="primary full" id="publishRecipeBtn">＋ ${t('publishAdd')}</button>`;$('#recipeCount').textContent=recipes.length;$$('.cook').forEach(b=>b.onclick=()=>openRecipe(b.dataset.name));$('#publishRecipeBtn')?.addEventListener('click',openPublishForm)}
function openRecipe(name){const r=recipes.find(x=>x.name===name);modal(`<h2>${r.icon} ${r.name}</h2><p><b>${t('time')}:</b> ${r.time}</p><div class="hint">${t('all')}</div><button class="primary full" id="recipeDone">${t('ok')}</button>`)}
function openPublishForm(){modal(`<h2>${t('publishAdd')}</h2><label>${t('name')}<input class="text-input" id="newName"></label><label>${t('ingredients')}<input class="text-input" id="newIngredients" placeholder="eggs, cheese, flour"></label><button class="primary full" id="publishNow">${t('publish')}</button>`)}
function renderInventory(){$('#inventoryList').innerHTML=state.inventory.map((x,i)=>`<div class="inventory-row"><span class="food-icon">${x.icon}</span><div class="row-main"><strong>${x.name}</strong><small>${x.qty}</small></div><button class="remove" data-i="${i}">×</button></div>`).join('');$$('.remove').forEach(b=>b.onclick=()=>{state.inventory.splice(+b.dataset.i,1);renderInventory();renderRecipes();toast(t('removed'))})}
function renderShopping(){$('#shoppingList').innerHTML=state.shopping.map(x=>`<label class="shopping-row"><input type="checkbox"><span class="food-icon">${x.icon}</span><div class="row-main"><strong>${x.name}</strong><small>${x.qty}</small></div></label>`).join('');$('#shoppingCount').textContent=state.shopping.length}
function addProduct(name,icon='🍎',qty='1 шт.'){state.inventory.push({name,icon,qty});renderInventory();renderRecipes()}
function simulateScan(){addProduct('Авокадо','🥑');toast('🥑 '+t('added')+' Авокадо');showScreen('inventory')}
function modal(h){$('#modalContent').innerHTML=h;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}function toast(v){const e=$('#toast');e.textContent=v;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}function showScreen(id){$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.screen===id));$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id))}
function startLazy(){if(Voice.supported){Voice.speak(t('greet'));setTimeout(()=>Voice.start(handleVoice),700);return}modal(`<h2>${t('greet')}</h2><p>${t('voiceoff')}</p><button class="primary full" id="simulateScan">${t('testscan')}</button>`)}
function handleVoice(text){const s=norm(text);const showWords={ru:['посмотри','покажи','закром','что у меня есть'],en:['show me','look','what do i have','pantry'],pl:['pokaż','co mam','zapasy'],de:['zeig','was habe ich','vorräte'],fr:['montre','qu’est-ce que j’ai','réserves'],es:['muéstrame','qué tengo','provisiones'],it:['mostra','cosa ho','scorte'],uk:['покажи','що в мене є','запаси'],zh:['看看','我有什么','食材'],ja:['見せて','何がある','食材']}[document.documentElement.lang]||[];if(showWords.some(x=>s.includes(norm(x)))){toast(t('heard')+' ✓');setTimeout(simulateScan,400);return}toast(t('heard')+' «'+text+'»')}
$('#languageButton').onclick=()=>openLanguagePicker();$('#closeModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};$$('.tab').forEach(x=>x.onclick=()=>showScreen(x.dataset.screen));$('#lazyBtn').onclick=startLazy;$('#voiceTop').onclick=()=>Voice.start(handleVoice);$('#scanBtn').onclick=()=>modal(`<h2>📷 ${t('what')}</h2><p>${t('testcam')}</p><button class="primary full" id="simulateScan">${t('testscan')}</button>`);$('#addProduct').onclick=()=>modal(`<h2>${t('add')}</h2><button class="choice" data-add="Яблоки|🍎">🍎 Яблоки</button><button class="choice" data-add="Морковь|🥕">🥕 Морковь</button><button class="choice" data-add="Хлеб|🍞">🍞 Хлеб</button><button class="choice" data-add="Лимон|🍋">🍋 Лимон</button>`);$('#aperitifBtn').onclick=()=>modal(`<h2>${t('aper')} 🥂</h2><p>${t('drink')}</p><button class="choice">🥂</button><button class="choice">🍷</button><button class="choice">🍹</button>`);$('#whereBuy').onclick=()=>findNearbyShops($('#shops'));
$('#modalContent').addEventListener('click',async e=>{if(e.target.id==='simulateScan'){closeModal();simulateScan();return}if(e.target.id==='recipeDone'){closeModal();return}const lang=e.target.closest('[data-lang]');if(lang){setLanguage(lang.dataset.lang);closeModal();return}const add=e.target.closest('[data-add]');if(add){const[n,i]=add.dataset.add.split('|');addProduct(n,i);closeModal();toast(t('added')+' '+n);return}if(e.target.id==='publishNow'){const name=$('#newName').value.trim(),ingredients=$('#newIngredients').value.split(',').map(x=>x.trim()).filter(Boolean);if(!name||!ingredients.length){toast(t('fill'));return}const result=await publishRecipe({name,time:'20 мин',icon:'🍽️',ingredients,tags:['user']});if(result.ok){closeModal();toast(t('published'));recipes=result.recipes.map(r=>({...r,need:r.ingredients||[],ready:(r.ingredients||[]).every(have)}));renderRecipes()}else toast(result.error)}});
(async()=>{const shared=await loadSharedLibrary();if(shared.length){recipes=shared.map(r=>({...r,ready:r.ingredients?.every(have)||false,need:r.ingredients||[],time:r.time||'—',icon:r.icon||'🍽️'}));renderRecipes()}})();renderRecipes();renderInventory();renderShopping();renderLanguage();