const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const state={inventory:[{name:'Яйца',qty:'6 шт.',icon:'🥚'},{name:'Помидоры',qty:'3 шт.',icon:'🍅'},{name:'Сыр',qty:'200 г',icon:'🧀'},{name:'Курица',qty:'500 г',icon:'🍗'},{name:'Сливки',qty:'200 мл',icon:'🥛'}],shopping:[{name:'Шампиньоны',qty:'300 г',icon:'🍄'},{name:'Картофель',qty:'1 кг',icon:'🥔'},{name:'Лук',qty:'2 шт.',icon:'🧅'}]};
let recipes=[{name:'Омлет с овощами',time:'15 мин',ready:true,need:[],icon:'🍳'},{name:'Курица с сыром',time:'30 мин',ready:true,need:[],icon:'🍗'},{name:'Запеканка',time:'35 мин',ready:true,need:[],icon:'🥘'},{name:'Паста с курицей и грибами',time:'25 мин',ready:false,need:['Шампиньоны','Сливки'],icon:'🍝'},{name:'Картофель с курицей',time:'40 мин',ready:false,need:['Картофель','Лук'],icon:'🥔'},{name:'Домашний майонез',time:'10 мин',ready:false,need:['Масло','Горчица','Лимон'],icon:'🥣'}];
const normalize=s=>String(s).toLowerCase().replace(/ё/g,'е');
const have=name=>state.inventory.some(x=>normalize(x.name).includes(normalize(name))||normalize(name).includes(normalize(x.name)));
function recalc(){recipes=recipes.map(r=>({...r,ready:r.need.length===0||r.need.every(have)}));}
function card(r){return `<article class="recipe"><div class="recipe-top"><div><h3>${r.icon} ${r.name}</h3><p>${r.ready?'Всё необходимое уже есть дома.':'Не хватает: '+r.need.filter(x=>!have(x)).join(', ')+'.'}</p></div></div><div class="recipe-actions"><small>⏱ ${r.time}</small>${r.ready?`<button class="outline cook" data-name="${r.name}">Открыть рецепт</button>`:`<span class="buy-label">Требуется докупить</span>`}</div></article>`}
function renderRecipes(){recalc();$('#readyRecipes').innerHTML=recipes.filter(r=>r.ready).map(card).join('');$('#buyRecipes').innerHTML=recipes.filter(r=>!r.ready).map(card).join('');$('#readyCount').textContent=recipes.filter(r=>r.ready).length;$('#allRecipes').innerHTML=recipes.map(card).join('')+`<button class="primary full" id="publishRecipeBtn">＋ Добавить рецепт в общую библиотеку</button>`;$('#recipeCount').textContent=recipes.length;$$('.cook').forEach(b=>b.onclick=()=>openRecipe(b.dataset.name));$('#publishRecipeBtn')?.addEventListener('click',openPublishForm);}
function openRecipe(name){const r=recipes.find(x=>x.name===name);modal(`<h2>${r.icon} ${r.name}</h2><p><b>Время:</b> ${r.time}</p><div class="hint">Тестовый рецепт подключён. На следующем этапе добавим полноценные шаги, порции и варианты замены ингредиентов.</div><button class="primary full" id="recipeDone">Понятно</button>`)}
function openPublishForm(){modal(`<h2>Добавить в общую библиотеку</h2><label>Название<input class="text-input" id="newName" placeholder="Например, сырники"></label><label>Ингредиенты<input class="text-input" id="newIngredients" placeholder="яйца, творог, мука"></label><label>Время<input class="text-input" id="newTime" value="20 мин"></label><button class="primary full" id="publishNow">Опубликовать</button><div class="hint">В тестовом сетевом контуре публикация идёт на Lenchay server. Если сервер не подключён, данные не отправляются.</div>`)}
function renderInventory(){$('#inventoryList').innerHTML=state.inventory.map((x,i)=>`<div class="inventory-row"><span class="food-icon">${x.icon}</span><div class="row-main"><strong>${x.name}</strong><small>${x.qty}</small></div><button class="remove" data-i="${i}">×</button></div>`).join('');$$('.remove').forEach(b=>b.onclick=()=>{state.inventory.splice(+b.dataset.i,1);renderInventory();renderRecipes();toast('Продукт удалён')});}
function renderShopping(){$('#shoppingList').innerHTML=state.shopping.map((x,i)=>`<label class="shopping-row"><input type="checkbox" data-i="${i}"><span class="food-icon">${x.icon}</span><div class="row-main"><strong>${x.name}</strong><small>${x.qty}</small></div></label>`).join('');$('#shoppingCount').textContent=state.shopping.length;}
function addProduct(name,icon='🍎',qty='1 шт.'){state.inventory.push({name,icon,qty});renderInventory();renderRecipes();}
function simulateScan(){addProduct('Авокадо','🥑');toast('Нашёл продукт: авокадо');showScreen('inventory');}
function modal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')}
function closeModal(){ $('#modal').classList.add('hidden') }
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function showScreen(id){$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.screen===id));$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));}
function startLazy(){const greeting='Привет. А ну-ка, покажи закрома.';if(window.Voice?.supported){Voice.speak(greeting);setTimeout(()=>Voice.start(handleVoice,()=>{}),700);return}modal(`<h2>${greeting}</h2><p>Голосовой режим в этом браузере недоступен. Можно сразу показать закрома через тестовую камеру.</p><button class="primary full" id="simulateScan">Показать закрома</button>`)}
function handleVoice(text){const t=normalize(text);if(t.includes('посмотри')||t.includes('покажи')||t.includes('закром')||t.includes('что у меня есть')){toast('Смотрю, что у тебя есть…');setTimeout(simulateScan,500);return}if(t.includes('добав')||t.includes('есть ')){const found=['яйц','помидор','сыр','куриц','сливк','картоф','лук','гриб','хлеб','яблок'];const hit=found.find(x=>t.includes(x));if(hit){const map={яйц:['Яйца','🥚'],помидор:['Помидоры','🍅'],сыр:['Сыр','🧀'],куриц:['Курица','🍗'],сливк:['Сливки','🥛'],картоф:['Картофель','🥔'],лук:['Лук','🧅'],гриб:['Шампиньоны','🍄'],хлеб:['Хлеб','🍞'],яблок:['Яблоки','🍎']};addProduct(...map[hit]);toast('Добавил: '+map[hit][0]);showScreen('inventory');return}}toast('Я услышал: «'+text+'». Уточни, что сделать.')}
$('#closeModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
$$('.tab').forEach(t=>t.onclick=()=>showScreen(t.dataset.screen));
$('#lazyBtn').onclick=startLazy;
$('#voiceTop').onclick=()=>{if(window.Voice?.supported)Voice.start(handleVoice);else toast('Голосовой ввод недоступен. Нажми «Начать ленивиться» или используй камеру.')};
$('#scanBtn').onclick=()=>modal(`<h2>📷 Посмотри закрома</h2><p>В этой тестовой версии камера имитируется. Реальное компьютерное зрение подключим следующим этапом.</p><button class="primary full" id="simulateScan">Запустить тестовое распознавание</button>`);
$('#addProduct').onclick=()=>modal(`<h2>Добавить продукт</h2><button class="choice" data-add="Яблоки|🍎">🍎 Яблоки</button><button class="choice" data-add="Морковь|🥕">🥕 Морковь</button><button class="choice" data-add="Хлеб|🍞">🍞 Хлеб</button><button class="choice" data-add="Лимон|🍋">🍋 Лимон</button>`);
$('#aperitifBtn').onclick=()=>modal(`<h2>У меня есть аперитивчик 🥂</h2><p>Выбери, что сегодня есть.</p><button class="choice" data-drink="🥂 Шампанское">🥂 Шампанское</button><button class="choice" data-drink="🍷 Вино">🍷 Вино</button><button class="choice" data-drink="🍹 Другой напиток">🍹 Другой напиток</button>`);
$('#whereBuy').onclick=()=>findNearbyShops($('#shops'));
$('#modalContent').addEventListener('click',async e=>{if(e.target.id==='simulateScan'){closeModal();simulateScan();return}if(e.target.id==='recipeDone'){closeModal();return}if(e.target.id==='closeChoice'){closeModal();return}const add=e.target.closest('[data-add]');if(add){const [name,icon]=add.dataset.add.split('|');addProduct(name,icon);closeModal();toast('Добавлено: '+name);return}const drink=e.target.closest('[data-drink]');if(drink){const d=drink.dataset.drink;modal(`<h2>${d}</h2><p>Вот что подходит к напитку из твоих продуктов.</p><div class="hint">Сыр, овощи и курица уже есть. Если захочешь, Лентяй добавит недостающие продукты в список покупок.</div><button class="primary full" id="closeChoice">Показать варианты</button>`);return}if(e.target.id==='publishNow'){const name=$('#newName').value.trim(),ingredients=$('#newIngredients').value.split(',').map(x=>x.trim()).filter(Boolean),time=$('#newTime').value.trim()||'20 мин';if(!name||!ingredients.length){toast('Заполни название и ингредиенты');return}const result=await publishRecipe({name,time,icon:'🍽️',ingredients,tags:['пользовательский']});if(result.ok){closeModal();toast('Рецепт опубликован в общей библиотеке');recipes=result.recipes.map(r=>({...r,need:r.ingredients||[],ready:(r.ingredients||[]).every(have)}));renderRecipes()}else toast(result.error)}});
(async()=>{const shared=await loadSharedLibrary();if(shared.length){recipes=shared.map(r=>({...r,ready:r.ingredients?.every(have)||false,need:r.ingredients||[],time:r.time||'—',icon:r.icon||'🍽️'}));renderRecipes();}})();
renderRecipes();renderInventory();renderShopping();
